name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Build Docker image
      run: docker build -t sunday:${{ github.sha }} .
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Debug info
      run: |
        echo "Image name: sunday"
        echo "SHA: ${{ github.sha }}"
        docker images

    - name: Tag Docker image
      run: |
        docker tag sunday:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/sunday:${{ github.sha }}
        echo "Tagging completed"

    - name: Push Docker image
      run: |
        echo "Pushing image ${{ secrets.DOCKER_USERNAME }}/sunday:${{ github.sha }}"
        docker push ${{ secrets.DOCKER_USERNAME }}/sunday:${{ github.sha }}