name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Build Docker image
      run: docker build -t sunday:${{ github.sha }} .
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Debug info
      run: |
        echo "Image name: sunday"
        echo "SHA: ${{ github.sha }}"
        docker images


    - name: Debug Docker username
      run: |
        echo "Docker username first letter: ${DOCKER_USERNAME:0:1}"
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

    - name: Tag Docker image
      run: |
        echo "Tagging image as ${DOCKER_USERNAME}/sunday:${{ github.sha }}"
        docker tag sunday:${{ github.sha }} ${DOCKER_USERNAME}/sunday:${{ github.sha }}
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

    - name: Push Docker image
      run: |
        echo "Pushing image ${DOCKER_USERNAME}/sunday:${{ github.sha }}"
        docker push ${DOCKER_USERNAME}/sunday:${{ github.sha }}
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}